package com.mycompany.myapp;
//test
import com.codename1.io.ConnectionRequest;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.NetworkEvent;
import com.codename1.io.NetworkManager;
import com.codename1.ui.Button;
import com.codename1.ui.Image;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BoxLayout;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;
    ConnectionRequest con;
    String url = "http://localhost/codename.txt";
    StringBuffer str = new StringBuffer();
    Form hi ;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");
        Toolbar.setGlobalToolbar(true);
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        hi= new Form(BoxLayout.y());
        Button getInfo=new Button();
        getInfo.setText("get Info");
        Label lb=new Label();
        try {
            Image img = Image.createImage("/giphy.gif");
            lb.setIcon(img);
        } catch (IOException ex) {}
        getInfo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                con = new ConnectionRequest(url);
                con.addResponseListener(new ActionListener<NetworkEvent>() {
                    @Override
                    public void actionPerformed(NetworkEvent evt) {
                        byte [] data=(byte[]) evt.getMetaData();
                        String ch=new String(data);
                        lb.setText(ch);
                        lb.setIcon(null);
                        hi.refreshTheme();
                    }
                });
        NetworkManager.getInstance().addToQueue(con);
            }
        });
        hi.add(lb);
        hi.add(getInfo);
        hi.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }

    public void destroy() {
    }

}
